require('basic-settings')
require('colorscheme')
require('installed-plugins')
require('mappings')
require('autocmds')
require('cmp-config')
require('gui-configs')
require('lsp')
require('treesitter-config')
require('autopairs')
require('gitsign-config')
require('toggleterm-config')
require('dapper-config')
-- require('diff')
-- require('neotree-settings')
